const D={employees:[["EMP-001","N. Ranjith Egodage","Senior Staff Coordinator","CTO Wing","Active"],["EMP-014","R.M.C. Rathnayake","Senior Staff Coordinator","Project Office","Active"],["EMP-028","Samarajeewa","Electrical Engineer","SKTIDP","Active"],["EMP-031","Gunarathne","Superintending Engineer","SKTIDP","Active"],["EMP-044","Jayasiri","Electrical Engineer","NHKGEP","Active"]],vehicles:[["WP CAA-0001","Toyota Hilux","2018","CEATP-I","Service due","Rs. 184,500"],["WP CAA-0002","Toyota Hilux","2019","CEATP-I","OK","Rs. 121,200"],["WP CAA-0003","Toyota Prius","2017","Project Office","OK","Rs. 96,800"],["WP CAA-0004","Toyota KDH","2018","CEATP-I","Fuel review","Rs. 212,600"],["WP CAA-0005","Toyota Hilux","2020","SKTIDP","OK","Rs. 88,400"],["WP CAA-0006","Toyota Hilux","2020","NHKGEP","Service due","Rs. 147,300"],["WP CAA-0007","Toyota KDH","2019","CEATP-I","OK","Rs. 134,700"],["WP CAA-0008","Toyota Hilux","2021","Project Office","OK","Rs. 74,900"]],wayleave:[["WL-001","NHKTL","T-001 → T-018","Kantalai","Private","Valuation"],["WL-002","SKTIDP","T-101 → T-132","Polonnaruwa","Private","Compensation"],["WL-003","NHKTL","T-201 → T-245","Trincomalee","Paddy","FCD Approval"],["WL-004","S-K Line","T-301 → T-325","Matale","Government","Survey"]],assets:[["FA-00125","Canon Photocopier","Accounts Branch","Rs. 285,000","Active"],["FA-00131","Water Dispenser","Accounts Branch","Rs. 48,500","Active"],["FA-00218","Split AC Unit","Project Office","Rs. 0","BOS Review"],["FA-00241","Office Workstation","Project Office","Rs. 132,000","Active"]],inventory:[["INV-0001","A4 Paper 80gsm","Stationery","120","Reorder 40"],["INV-0002","Printer Toner","IT Consumables","18","OK"],["INV-0003","Safety Helmet","PPE","65","OK"],["INV-0004","Cable Marker","Electrical","22","Reorder 25"]],documents:[["DOC-2026-041","PM Assignment Letter","HR / Admin","16-Sep-2026","Controlled"],["DOC-2026-052","Pre-Bid Meeting Record","Procurement","11-Sep-2026","Controlled"],["DOC-2026-067","AC Asset Transfer File","Finance / Assets","25-Sep-2026","Review"],["DOC-2026-071","Vehicle Tax Advance","Finance","28-Sep-2026","Approved"]]};

const groups=[["WORKSPACE",[["dashboard","Executive Dashboard","index.html"],["hr","HR & Employees","hr.html"],["wayleave","Wayleave Management","wayleave.html"],["fleet","Fleet & Fuel","fleet.html"]]],["CONTROL",[["inventory","Inventory & Stores","inventory.html"],["assets","Fixed Assets","assets.html"],["procurement","Procurement / TEC / BEC","procurement.html"],["finance","Finance & Expenditure","finance.html"]]],["OFFICE",[["letters","AI Office / Letters","letters.html"],["documents","Documents","documents.html"],["admin","Administration","admin.html"]]]];

function esc(x){return String(x).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function pill(x){let c=/ok|active|approved|controlled/i.test(x)?"ok":/pending|review|due|valuation|reorder|approval|clarification/i.test(x)?"review":"pending";return `<span class="pill ${c}">${esc(x)}</span>`}
function shell(page,title,sub,body){let nav=groups.map(g=>`<div class="lbl">${g[0]}</div><div class="nav">${g[1].map(n=>`<a class="${page==n[0]?"active":""}" href="${n[2]}">${n[1]}</a>`).join("")}</div>`).join("");document.getElementById("app").innerHTML=`<div class="shell"><aside class="side"><div class="brand"><div class="mark">N1</div><div><b>NTNSP ONE</b><small>CEATP-I DIGITAL WORKPLACE</small></div></div>${nav}<div class="footer">V3 Prototype • GitHub-ready</div></aside><main class="main"><header class="top"><span class="muted">NTNSP / CEATP-I / ${title}</span><div><input placeholder="Search…"><span class="avatar">NR</span></div></header><section class="content">${body}</section></main></div><div id="modal" class="modal"></div>`}
function head(t,p,a=""){return `<div class="head"><div><h1>${t}</h1><p>${p}</p></div><div class="actions">${a}</div></div>`}
function k(l,n,s){return `<div class="kpi"><small>${l}</small><strong>${n}</strong><span class="${/due|review/i.test(s)?"warn":"up"}">${s}</span></div>`}
function table(h,rows){return `<div class="tablewrap"><table class="table"><thead><tr>${h.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>`<td>${i==r.length-1?pill(x):esc(x)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function modal(title,html){document.getElementById("modal").innerHTML=`<div class="modalbox"><div class="mh"><h3>${title}</h3><button onclick="closeM()">×</button></div>${html}</div>`;document.getElementById("modal").classList.add("show")}
function closeM(){document.getElementById("modal").classList.remove("show")}
function add(type){let names={employees:["ID","Employee","Designation","Unit","Status"],vehicles:["Registration","Vehicle","Year","Assigned To","Status","YTD Cost"],assets:["Asset ID","Description","Location","Value","Status"],inventory:["Code","Description","Category","Qty","Status"],documents:["ID","Title","Category","Date","Status"],wayleave:["WNo","Line","Tower Range","DS","Land Type","Status"]}[type];modal("Add Record",`<form class="form" onsubmit="save(event,'${type}')">${names.map(n=>`<div class="field"><label>${n}</label><input required></div>`).join("")}<div class="full"><button class="btn primary">Save</button></div></form>`)}
function save(e,type){e.preventDefault();D[type].push([...e.target.querySelectorAll("input")].map(x=>x.value));localStorage.setItem("ntnsp_"+type,JSON.stringify(D[type]));closeM();location.reload()}
function modulePage(page,title,sub,type,h,a){shell(page,title,sub,head(title,sub,a)+`<div class="card">${table(h,D[type])}</div>`)}
function dashboard(){shell("dashboard","Executive Dashboard","Management view of CEATP-I operations.",head("Executive Dashboard","30 September 2026 • Project Management Overview",`<button class="btn secondary" onclick="location.reload()">Refresh</button>`)+`<div class="cards">${k("Active Employees","86","↑ 4 this quarter")}${k("Wayleave Records","1,248","↑ 72 updated")}${k("Fleet Maintenance","Rs. 1.06M","8 vehicles • YTD","review")}${k("Procurement Packages","12","4 in evaluation","review")}</div><div class="grid2"><div class="card"><h3>Project Expenditure • 2021–2026</h3><div class="chart">${[48,61,55,73,82,94].map((h,i)=>`<div class="col"><div class="bar" style="height:${h}%"></div><small>${2021+i}</small></div>`).join("")}</div></div><div class="card"><h3>Management Alerts</h3><div class="list"><div class="item"><span>2 vehicles approaching service</span>${pill("Service due")}</div><div class="item"><span>AC asset requires BOS review</span>${pill("Review")}</div><div class="item"><span>NHKGEP clarification pending</span>${pill("Clarification")}</div><div class="item"><span>4 wayleave cases awaiting valuation</span>${pill("Valuation")}</div></div></div></div><div class="grid2"><div class="card"><h3>Wayleave Progress</h3><p class="muted">942 of 1,248 sample records processed</p><div style="height:8px;background:#edf1f6;border-radius:8px"><div style="width:78%;height:100%;background:#2d6cdf;border-radius:8px"></div></div></div><div class="card"><h3>Fleet Availability</h3><p class="muted">7 / 8 vehicles available</p><div style="height:8px;background:#edf1f6;border-radius:8px"><div style="width:88%;height:100%;background:#18a7b8;border-radius:8px"></div></div></div></div>`)}
function loadXLSX(){return window.XLSX?Promise.resolve():new Promise((ok,no)=>{let s=document.createElement("script");s.src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js";s.onload=ok;s.onerror=()=>no(new Error("Could not load the Excel reader (check internet connection)"));document.head.appendChild(s)})}
function parseEmployees(buf){let wb=XLSX.read(buf,{type:"array"}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:"",raw:false}).filter(r=>r.some(c=>String(c).trim()));if(rows.length<2)throw new Error("No data rows found");let h=rows[0].map(c=>String(c).trim().toLowerCase()),find=(re,d)=>{let i=h.findIndex(x=>re.test(x));return i<0?d:i},ix=[find(/^(id|emp.*(id|no)|no)$/,0),find(/name|^employee$/,1),find(/designation|position|title/,2),find(/unit|division|project|office/,3),find(/status/,4)];return rows.slice(1).map(r=>ix.map(i=>String(r[i]??"").trim()))}
function setEmployees(rows){D.employees=rows;localStorage.setItem("ntnsp_employees",JSON.stringify(rows));hr()}
function importExcel(inp){let f=inp.files[0];if(!f)return;Promise.all([loadXLSX(),f.arrayBuffer()]).then(([_,b])=>setEmployees(parseEmployees(b))).catch(e=>alert("Import failed: "+e.message))}
function loadRepoExcel(){loadXLSX().then(()=>fetch("data/employees.xlsx?"+Date.now())).then(r=>{if(!r.ok)throw new Error("data/employees.xlsx was not found on the site");return r.arrayBuffer()}).then(b=>setEmployees(parseEmployees(b))).catch(e=>alert("Load failed: "+e.message))}
function resetEmployees(){localStorage.removeItem("ntnsp_employees");location.reload()}
function hr(){modulePage("hr","HR & Employees","Employee directory and workforce status.","employees",["ID","Employee","Designation","Unit","Status"],`<input type="file" id="xf" accept=".xlsx,.xls,.csv" hidden onchange="importExcel(this)"><button class="btn secondary" onclick="document.getElementById('xf').click()">Import Excel</button><button class="btn ghost" onclick="loadRepoExcel()">Load data/employees.xlsx</button><button class="btn ghost" onclick="resetEmployees()">Reset</button><button class="btn primary" onclick="add('employees')">＋ Add</button>`)}

function fleet(){modulePage("fleet","Fleet & Fuel","8-vehicle maintenance and fuel monitoring.","vehicles",["Registration","Vehicle","Year","Assigned To","Status","YTD Cost"],`<button class="btn primary" onclick="add('vehicles')">＋ Add Vehicle</button>`)}
function assets(){modulePage("assets","Fixed Assets","Asset register and Board of Survey workflow.","assets",["ID","Description","Location","Value","Status"],`<button class="btn primary" onclick="add('assets')">＋ Add Asset</button>`)}
function inventory(){modulePage("inventory","Inventory & Stores","Stock balances and reorder monitoring.","inventory",["Code","Description","Category","Qty","Status"],`<button class="btn primary" onclick="add('inventory')">＋ Add Item</button>`)}
function documents(){modulePage("documents","Documents","Controlled project correspondence register.","documents",["ID","Document","Category","Date","Status"],`<button class="btn primary" onclick="add('documents')">＋ Register</button>`)}
function procurement(){let r=[["CEATP/ICB/01","Transmission Line Package A","ICB","TEC Evaluation","25-Jun-2026","6 Bids"],["CEATP/ICB/02","GSS Augmentation","ICB","Financial Opening","Aug-2026","4 Bids"],["CEATP/NCB/07","Vehicle Services","NCB","Contract","Sep-2026","3 Bids"],["CEATP/ICB/04","NHKGEP Package B","ICB","Clarification","Sep-2026","5 Bids"]];shell("procurement","Procurement / TEC / BEC","Tender package pipeline and evaluation status.",head("Procurement / TEC / BEC","Management tracker",`<button class="btn primary" onclick="modal('New Package','<div class=\\'notice\\'>V3 foundation ready. Connect this module to the database in V4.</div>')">＋ New Package</button>`)+`<div class="card">${table(["Package","Scope","Method","Stage","Date","Bids"],r)}</div>`)}
function finance(){shell("finance","Finance & Expenditure","Vote-wise expenditure and control summary.",head("Finance & Expenditure","Illustrative management figures")+`<div class="cards">${k("YTD Expenditure","Rs. 184.6M","Illustrative")}${k("Vehicle Maintenance","Rs. 1.06M","8 vehicles")}${k("Fuel Expenditure","Rs. 3.42M","YTD")}${k("Wayleave Payments","Rs. 72.8M","Processed")}</div><div class="grid2"><div class="card"><h3>Vote-wise Trend</h3><div class="chart">${[52,68,47,79,72,91].map((h,i)=>`<div class="col"><div class="bar" style="height:${h}%"></div><small>${2021+i}</small></div>`).join("")}</div></div><div class="card"><h3>Control Notes</h3><div class="list"><div class="item"><span>VAT documentation</span>${pill("Review")}</div><div class="item"><span>Asset transfers</span>${pill("Pending")}</div><div class="item"><span>Vehicle advances</span>${pill("Approved")}</div></div></div></div>`)}
function wayleave(){shell("wayleave","Wayleave Management","Route → tower → span → parcel → owner → tree → valuation → compensation.",head("Wayleave Management","GIS-ready transmission corridor register",`<button class="btn secondary" onclick="modal('Workflow','<div class=\\'notice\\'>1. Route/Tower → 2. Parcel/Owner → 3. Trees/Valuation → 4. Compensation/Payment</div>')">Workflow</button><button class="btn primary" onclick="add('wayleave')">＋ New</button>`)+`<div class="grid2"><div class="card"><h3>Transmission Corridor Map</h3><p class="muted">Schematic V3 map — ready for real GIS coordinates later.</p><div class="map"><div class="route"></div>${[[19,25],[31,37],[43,29],[54,47],[67,39],[78,59]].map(p=>`<i class="tower" style="left:${p[0]}%;top:${p[1]}%"></i>`).join("")}</div></div><div class="card"><h3>Case Status</h3><div class="list"><div class="item"><span>Survey completed · 942 parcels</span>${pill("Approved")}</div><div class="item"><span>Valuation · 186 parcels</span>${pill("Valuation")}</div><div class="item"><span>FCD / statutory · 74</span>${pill("Approval")}</div><div class="item"><span>Compensation · 46</span>${pill("Pending")}</div></div></div></div><div class="card" style="margin-top:17px"><h3>Recent Wayleave Cases</h3>${table(["WNo","Line","Tower Range","DS","Land Type","Status"],D.wayleave)}</div>`)}
function letters(){shell("letters","AI Office / Letter Generator","Template-driven official correspondence assistant.",head("AI Office / Letter Generator","Generate a first draft from structured information")+`<div class="grid2"><div class="card"><h3>Draft Builder</h3><form id="lf" class="form" onsubmit="gen(event)"><div class="field"><label>Letter Type</label><select><option>Request for Approval</option><option>Assignment of Duties</option><option>Appreciation</option><option>Asset / BOS Recommendation</option></select></div><div class="field"><label>Recipient</label><input value="Chief Technical Officer"></div><div class="field full"><label>Subject</label><input value="Request for necessary approval"></div><div class="field full"><label>Key facts</label><textarea>Please consider the matter described below and provide the necessary approval to proceed in accordance with applicable procedures.</textarea></div><div class="full"><button class="btn primary">Generate Draft</button></div></form></div><div class="card"><h3>Generated Draft</h3><textarea id="out" style="width:100%;height:360px;border:1px solid #e5eaf1;border-radius:9px;padding:12px">Select the fields and click Generate Draft.</textarea></div></div>`)}
function gen(e){e.preventDefault();let x=e.target.querySelectorAll("input,textarea"),to=x[0].value,sub=x[1].value,b=x[2].value;document.getElementById("out").value=`To: ${to}\n\nSubject: ${sub}\n\nDear Sir,\n\n${b}\n\nIn view of the above, your consideration and necessary approval are kindly requested to proceed with the matter.\n\nYours faithfully,\n\nProject Manager\nCEATP-I\nNTNSP (Pvt) Ltd\n\n[Draft — review before official issue]`}
function admin(){shell("admin","Administration","Portal configuration and V4 readiness.",head("Administration","V3 prototype administration")+`<div class="grid2"><div class="card"><h3>System Status</h3><div class="list"><div class="item"><span>Frontend</span>${pill("Active")}</div><div class="item"><span>Demo data</span>${pill("Active")}</div><div class="item"><span>Authentication</span>${pill("Review")}</div><div class="item"><span>Database</span>${pill("Pending")}</div></div></div><div class="card"><h3>V4 Backend Direction</h3><p class="muted">Connect the V3 interface to secure authentication, role permissions, PostgreSQL, document storage, audit logs and reporting.</p><div class="notice">The V3 login and localStorage are demonstration only and must not be used for confidential production data.</div></div></div>`)}
function login(){document.getElementById("app").innerHTML=`<div class="login"><div class="loginbox"><div class="mark">N1</div><h1>Welcome back</h1><p>NTNSP ONE • CEATP-I Digital Workplace</p><form onsubmit="event.preventDefault();location.href='index.html'"><div class="field"><label>Username</label><input value="demo.user"></div><div class="field"><label>Password</label><input type="password" value="demo123"></div><button class="btn primary">Sign in</button></form><div class="notice" style="margin-top:15px">Prototype login only. Production authentication requires a secure backend.</div></div></div>`}
Object.keys(D).forEach(k=>{let x=localStorage.getItem("ntnsp_"+k);if(x)try{D[k]=JSON.parse(x)}catch{}})
const p=document.body.dataset.page;({dashboard,hr,wayleave,fleet,inventory,assets,procurement,finance,letters,documents,admin,login}[p]||dashboard)();